version: '3.9'

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-yourpass}
      POSTGRES_DB: ${POSTGRES_DB:-jobrunner}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - jobnetwork
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT:-Development}
      ASPNETCORE_URLS: ${ASPNETCORE_URLS:-http://+:80}
      ConnectionStrings__Default: "Host=${POSTGRES_HOST:-db};Database=${POSTGRES_DB:-jobrunner};Username=${POSTGRES_USER:-postgres};Password=${POSTGRES_PASSWORD:-yourpass}"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - jobnetwork
    restart: always

volumes:
  pgdata:

networks:
  jobnetwork:
    driver: bridge